### ISSUE TITLE
[BUG] - Segments will not display due to "New Line" labeling

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARCOP#251] opened 2024-03-21 13:50 UTC
### Which app?

Dashboards

### Describe the Device, Operating System, and Browser

Laptop, Windows, Edge

### Describe the bug

Search segments (polygon feature layer) will not display unless Segment Name field is filled out. This fields is used as a label on the map so it is potentially a labeling issue bug. 

### Expected Behavior

The search segment features should display even when these fields are not filled out. 

### Reproduction Steps & Sample

1. Go to https://experience.arcgis.com/experience/9051a07ffd1947bbb395e9f9b4088f85/page/Intel-Manager-1_0/
2. Using the Smart Editor, add a new search segment (any kind) and leave the Segment Name field blank

![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/4256979/32df62e9-906d-4280-9734-d42a22dae794)

3. Go to the Tactical Dashboard, navigate to the segments you added
4. Notice the segments where Search Segment Name is blank, they do not display. 

![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/4256979/c383ac30-49a7-47e4-9024-729b8e0ccdf2)

### Other Relevant Info

This appears to have started AFTER the ArcGIS Online release. Here is the version of Edge I am using 
![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/4256979/98803a1e-ff25-4a1b-a113-91994f5bf36f)

Also on Chrome, I will try the update next
![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/4256979/fe93ff5e-1395-4368-9b3f-6a7479134c8f)

Confirmed that this is not caused by Dashboard embedded in Experience Builder, tested on stand alone Dashboard 
https://napsg.maps.arcgis.com/apps/dashboards/a6637762c84a47a7958a4e3601cd071f

Confirmed that this is not caused by Dashboard applications, tested in the web map 
https://napsg.maps.arcgis.com/apps/mapviewer/index.html?webmap=ae14c820e00d492d90428aefaa01422a

Confirmed that this is not caused by web map viewer, happens even in the Visualization tab, *so I think this is a Javascript API issue* https://napsg.maps.arcgis.com/home/item.html?id=5f67f852d0f043799d7509efdaa16ad2&sublayer=5#visualize

![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/4256979/f1ca9e9f-4674-4a38-99a5-2e70c4d4f53c)

The arcade expression being used is $feature["segment_designation"] + TextFormatting.NewLine + $feature["team_name"]. Perhaps it is an issue with "new line" expression? When I turn lables off - the issue disappears. Also if I keep the expression simple without NewLine, it goes away.

![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/4256979/9ba98aa6-74cf-4ba3-9af5-a7615414b054)

### Priority impact

p1 - time sensitive

### Impact

This will be confusing for end users who are quickly drawing search segments and intend to go back later to name them.

**Comment by pjdohertygis** [comment] 2024-03-21 14:11
Reported to Esri, you have successfully submitted your support request. Your new case number is: 03585008.

**Comment by pjdohertygis** [comment] 2024-03-22 16:55
Just finished an Esri Support call. We confirmed that we can replicate the issue if we clone the SARCOP feature layer, but she is not able to replicate from a fresh layer itself. We were able to get some error codes and am sending her a HAR file for now. We will go ahead and fix our web map labels for now and Esri will use this cloned feature layer for testing. 

https://napsg.maps.arcgis.com/home/item.html?id=b61eff6326204d20b69aeee6f89687cf#overview

**Comment by avezina** [comment] 2024-03-22 17:00
Web Map used in WAB: https://napsg.maps.arcgis.com/home/item.html?id=904575e13cf04ebfb9bdfc4ee0f48cbb
Loaded in MV Classic (downgraded to JS 3.x) vs. new MV (JS 4.x)
![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/50338557/b81a0930-ff4c-416d-851f-339564c3b028)

Compare for location Owensboro, KY

JS SDK 4.28: https://codepen.io/avezina/pen/MWRmogd
![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/50338557/5786a530-b796-42b3-b55c-2b45e3694407)

JS SDK 4.29: https://codepen.io/avezina/pen/GRLmEKO
![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/50338557/5130e6fd-e669-4f9a-89aa-92da06e96931)

Confirms that it looks like may be regression for JS SDK between 4.28 and 4.29

**Comment by pjdohertygis** [comment] 2024-03-22 17:18
Workaround for now. 

1. Get rid of the Arcade expression in segment label.
2. Create two labels. One is Segment, One is Team Name.
3. Drag Team Name below Segment, then match the format of Segment. 

![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/4256979/f9391298-bbef-446a-acc7-c70bb5bfaa68)

**Comment by pjdohertygis** [comment] 2024-03-27 18:29
1. Create a new feature layer from Content. Polygon only. 
2. Add two fields (Field 1 and Field 2) as text, 256 limit.
3. In visualization tab create label with expression $feature.Field1 + TextFormatting.NewLine + $feature.Field2
4. In web map viewer add 4 polygon features. 
- Add text to Field 1 and Field 2
- Add text to Field 1 only
- Add text to Field 2 only
- Add no text to either

At this point in time, I see that the fourth feature with neither Field 1 or 2 filled out, is entirely blank on screen but does show up in the data table. And after returning the map, I know see only partial drawing. 

 In the below "1" is with both fields filled out. "4" is with no fields filled out. It seems really inconsistent, but I can definitely observe the issue. 
 
![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/4256979/9eb5d65f-ecec-4180-bd58-03864b00c2f3)

Here is the error I am picking up in the console 
![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/4256979/81816510-99e5-4445-9f72-8c02e8ffef67)
![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/4256979/89cc9e29-c1c3-4a40-98dc-e7a60f0296f0)

**Comment by pjdohertygis** [comment] 2024-03-28 19:44
This now logged as a defect, will monitor until fixed and then close this issue. We will have to go back and fix our maps with the new script. Field Maps and QuickCapture can't read the "two label" workaround implemented above. 
BUG-000166346 - Polygons display incorrectly in JS API 4.29 when using TextFormatting.NewLine expression in the labels.

**Comment by oviera-napsg** [comment] 2024-08-23 18:27
Addressed by ESRI - closing.

**Closed by oviera-napsg** 2024-08-23 18:27 UTC
Labels: Bug, ArcGIS Online

**Comment by pjdohertygis** [comment] 2025-03-27 19:06
@oviera-napsg  @ChristopherPierson 

do you think we need to reopen this issue? 

![Image](https://github.com/user-attachments/assets/402a0109-6ac5-4995-9458-c1cec1e8c84a)

**Comment by oviera-napsg** [comment] 2025-03-27 19:44
> [@oviera-napsg](https://github.com/oviera-napsg) [@ChristopherPierson](https://github.com/ChristopherPierson)
> 
> do you think we need to reopen this issue?
> 
> ![Image](https://github.com/user-attachments/assets/402a0109-6ac5-4995-9458-c1cec1e8c84a)

Labels seem to work on my end - I was not able to recreate the absent label behavior @ChristopherPierson is seeing.

And yes, we will need to configure Worksite pop-ups.  I can work on that at the master level if Chris can propagate afterwards.

**Comment by oviera-napsg** [comment] 2025-04-08 04:35
@ChristopherPierson  - confirming label behavior was corrected?

Worksite pop-ups completed on v10 master 7 April 2025--passed on to Chris P for propagation.

**Comment by ChristopherPierson** [comment] 2025-04-10 02:55
@oviera-napsg sorry just replying now, but yes worksite labeling was corrected to display in QC. Not sure why QC didn't like the multiline label. Had to make the label an expression which means both the name and occupancy are the same font size now.
